"""20250226_0003_newmigr.py

Revision ID: eab24a557864
Revises: 69389e98c304
Create Date: 2026-02-27 00:15:08.462247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eab24a557864'
down_revision = '69389e98c304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###