"""add_tags_to_leads

Revision ID: e4e35b6d792e
Revises: f410b7cde7b6
Create Date: 2026-03-02 01:41:35.126155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4e35b6d792e'
down_revision = 'f410b7cde7b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###