"""add_leads_indexes

Revision ID: f410b7cde7b6
Revises: a9b8c7d6e5f4
Create Date: 2026-03-02 01:39:32.099927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f410b7cde7b6'
down_revision = 'a9b8c7d6e5f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_card_messages_chat_message'), table_name='lead_card_messages')
    op.drop_index(op.f('ix_lead_card_messages_lead_active'), table_name='lead_card_messages')
    op.create_index('ix_leads_created_at', 'leads', ['created_at'], unique=False)
    op.create_index('ix_leads_status', 'leads', ['status'], unique=False)
    op.drop_constraint(op.f('managers_tg_id_key'), 'managers', type_='unique')
    op.create_index(op.f('ix_managers_tg_id'), 'managers', ['tg_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_managers_tg_id'), table_name='managers')
    op.create_unique_constraint(op.f('managers_tg_id_key'), 'managers', ['tg_id'])
    op.drop_index('ix_leads_status', table_name='leads')
    op.drop_index('ix_leads_created_at', table_name='leads')
    op.create_index(op.f('ix_lead_card_messages_lead_active'), 'lead_card_messages', ['lead_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_lead_card_messages_chat_message'), 'lead_card_messages', ['chat_id', 'message_id'], unique=False)
    # ### end Alembic commands ###